name: Dynamic Clash Sync

on:
  schedule:
    - cron: '0 3 * * *' # 每天UTC时间3点运行
  workflow_dispatch:

jobs:
  sync-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync config files
        run: |
          wget https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/refs/heads/main/cfg/Custom_Clash.ini

      - name: Commit changes
        run: |
          git config --global user.name "Clash Rule Bot"
          git config --global user.email "clash-bot@users.noreply.github.com"
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-Update: Filter special nodes"
            git push
          else
            echo "No changes to commit"
          fi
